sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "31949361+Thirdsense3@users.noreply.github.com"
  - git config --global user.name "Thirdsense3"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "IDtYIRhk4Ycu1Qbq4VtVDJytldz6FdVNuyAiSvxvBiEAGiEDOM5SgDxfPUWqs+tzPcW/8ne+F0fohL+2fLUl8ZFkXyvlo5+QtrHaA53vKLt2RhXuUnm/7hwXVGI+bLYjGiQRhu4dUZDCpJwPR4IlPtiRv05oP1wyA95TQhwpTj6G3c7Ra7nhYVuU6SNNNL56Sl4zYchZJKusAz9xZTxX0Z/wy9mkAEvi+PoyqdSNc9jPDuq6YajEoHchGKl3PwUwJ3ubbMTdNzFUx+Mvut0BQd3alp5H2FAy8PApmK7fh/S/alQkCoURLoLw1qmG5GIXOGnCl3fdjNjlbRZDF+p7senkQ7AYDX2Lfu/l4I7djS90VzOpIW39aFa7GENYCv51bubXMTKazUg0+VZTUiwiDy6OVr+RVlc2Y2IN8cYBw8RgSEzS+MED5oBTFQ1gJuCzOl08OnsxXrybmLKmGetQf2yaiU446QctOF9vaR0D6lfJsj4kg7NsCo6lbQCmwmfgzLbCt6+q+0d+VPJKmrR5w+x7MY+EtW9hdYsPacQfKIBOr/89Vuw7R4mdMipiQokkbOUEnLcI9ccX61Tbbf7TUEE0wA1SLsY08IcF4xuW7STJPyMgitFVfE2vXoReqB4BCNeZT8K9mjKokcgmG5d2xeMq5JIXAu739ldgkFeiG5Q="
branches:
  only:
    - master